-- Minimal DDL to support ImageVersionWatermark placements.
-- Safe to run multiple times.

CREATE TABLE IF NOT EXISTS public.image_version_watermarks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_version_id uuid NOT NULL,
  watermark_id integer,
  text character varying NOT NULL,
  position character varying NOT NULL,
  opacity integer NOT NULL DEFAULT 60,
  font character varying NOT NULL DEFAULT 'Inter',
  sort_order integer NOT NULL DEFAULT 0,
  applied_at timestamp without time zone DEFAULT now(),
  CONSTRAINT image_version_watermarks_image_version_id_fkey
    FOREIGN KEY (image_version_id) REFERENCES public.image_versions(id) ON DELETE CASCADE,
  CONSTRAINT image_version_watermarks_watermark_id_fkey
    FOREIGN KEY (watermark_id) REFERENCES public.watermarks(id)
);

CREATE INDEX IF NOT EXISTS image_version_watermarks_image_version_id_idx
  ON public.image_version_watermarks (image_version_id);

CREATE INDEX IF NOT EXISTS image_version_watermarks_watermark_id_idx
  ON public.image_version_watermarks (watermark_id);
